language: cpp
dist: trusty
sudo: required

script:
    - cd Inputs
    - ./input_generator.sh 1000 999 0 0
    - ./input_generator.sh 10000 9999 0 0
    - ./input_generator.sh 100000 99999 0 0
    - ./input_generator.sh 1000000 999999 0 0
    - ./input_generator.sh 10000000 9999999 0 0
    - ./input_generator.sh 1000 0 1000 0
    - ./input_generator.sh 10000 0 10000 0
    - ./input_generator.sh 100000 0 100000 0
    - ./input_generator.sh 1000000 0 1000000 0
    - ./input_generator.sh 10000000 0 10000000 0
    - cd ..
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest -V

before_install:
    - eval "${MATRIX_EVAL}"

matrix:
  include:

    ######## OSX CLANG ########
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++"
      before_script:
        - brew update && brew cask uninstall oclint && brew install llvm@3.9 && brew link --overwrite llvm@3.9 --force
        - brew tap homebrew/science && brew install r
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++"
      before_script:
        - brew update && brew cask uninstall oclint && brew install llvm && brew link --overwrite llvm --force
        - brew tap homebrew/science && brew install r

    ######## OSX GCC ########
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      before_script:
        - brew update && brew cask uninstall oclint && brew install gcc@4.9
        - brew tap homebrew/science && brew install r
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      before_script:
        - brew update && brew cask uninstall oclint && brew install gcc@5
        - brew tap homebrew/science && brew install r
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      before_script:
        - brew update && brew cask uninstall oclint && brew install gcc@6
        - brew tap homebrew/science && brew install r
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_script:
        - brew update && brew cask uninstall oclint && brew install gcc
        - brew tap homebrew/science && brew install r

    ######## LINUX CLANG ########
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - r-base
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
      before_script:
        - sudo sed -i 's/trusty/zesty/g' /etc/apt/sources.list
        - sudo apt-get update
        - sudo apt-get install libstdc++-6-dev
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - r-base
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - clang-5.0
            - r-base
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    ######## LINUX GCC ########
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - r-base
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - r-base
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - r-base
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os : linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - r-base
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
