language: cpp
dist: xenial

script:
    - cd Inputs
    - ./input_generator.sh 1000 999 0 0
    - ./input_generator.sh 10000 9999 0 0
    - ./input_generator.sh 100000 99999 0 0
    - ./input_generator.sh 1000000 999999 0 0
    - ./input_generator.sh 10000000 9999999 0 0
    - ./input_generator.sh 1000 0 1000 0
    - ./input_generator.sh 10000 0 10000 0
    - ./input_generator.sh 100000 0 100000 0
    - ./input_generator.sh 1000000 0 1000000 0
    - ./input_generator.sh 10000000 0 10000000 0
    - cd ..
    - mkdir build && cd build
    - cmake -D CMAKE_BUILD_TYPE=Release ..
    - cmake --build . --config Release
    - ctest -V

before_script:
    - eval "${MATRIX_EVAL}"

matrix:
  include:

    ######## OSX CLANG ########
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++"
      before_install:
        - brew update
        - brew install llvm@3.9 && brew link --overwrite llvm@3.9 --force
      install: &mac_extra
        - brew install r
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++"
      before_install:
        - brew update
        - brew install llvm@4 && brew link --overwrite llvm@4 --force
      install: *mac_extra
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++"
      before_install:
        - brew update
        - brew install llvm@5 && brew link --overwrite llvm@5 --force
      install: *mac_extra
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++"
      before_install:
        - brew update
        - brew install llvm@6 && brew link --overwrite llvm@6 --force
      install: *mac_extra
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++"
      before_install:
        - brew update
        - brew install llvm@7 && brew link --overwrite llvm@7 --force
        - export PATH="/usr/local/opt/llvm/bin:$PATH"
        - export LDFLAGS="-L/usr/local/opt/llvm/lib"
        - export CPPFLAGS="-I/usr/local/opt/llvm/include"
      install: *mac_extra

    ######## OSX GCC ########
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      before_install:
        - brew update
        - brew install gcc@4.9
      install: *mac_extra
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      before_install:
        - brew update
        - brew install gcc@5
      install: *mac_extra
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      before_install:
        - brew update
        - brew install gcc@6
      install: *mac_extra
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
        - brew update
        - brew install gcc
      install: *mac_extra
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      before_install:
        - brew update
        - brew link gcc@8
      install: *mac_extra

    ######## LINUX CLANG ########
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-3.9
          packages:
            - clang-3.9
            - r-base
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-4.0
          packages:
            - clang-4.0
            - r-base
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-5.0
          packages:
            - clang-5.0
            - r-base
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
            - r-base
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - r-base
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
    ######## LINUX GCC ########
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - r-base
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - r-base
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - r-base
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os : linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - r-base
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os : linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - r-base
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
